// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2017.commands;
import org.usfirst.frc253.Code2017.Robot;
import edu.wpi.first.wpilibj.Timer;

/**
 *
 */
public class AutoRight extends SensorData {

    public AutoRight() {
    	super();
        requires(Robot.drivetraintank);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double gyroAngle = gyro1.getAngle();
    	Timer myTimer = new Timer();
    	
    	myTimer.start();
    	if(myTimer.get() < 2.5){
    		new StraightDrive();
    	}
    	myTimer.stop();
    	myTimer.reset();
    	
    	while(gyroAngle < -45){ //might be 45
    		new SpinCounterwise();
    	}
    	
    	myTimer.start();
    	if(myTimer.get() < 1.0){
    		new StraightDrive();
    	}
    	myTimer.stop();
    	myTimer.reset();
    	
//    	new GearAutoCorrect(); //may or may not use
    	
    	myTimer.start();
    	if(myTimer.get() < 0.5){
    		new DeployGear();
    	} else if(myTimer.get() < 1.0){
    		new Retract();
    	}
    	myTimer.stop();
    	myTimer.reset();
    	end();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetraintank.setLeft_Back(0);
    	Robot.drivetraintank.setLeft(0);
    	Robot.drivetraintank.setRight(0);
    	Robot.drivetraintank.setRight_Back(0);
    	Robot.gearFlip.FullStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
